# Generated by Django 4.2 on 2024-09-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0007_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team/')),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
            ],
        ),
    ]
