# Generated by Django 4.2 on 2024-09-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0008_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='timeline/')),
            ],
        ),
    ]
