# Generated by Django 4.2 on 2024-09-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0011_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
