# Generated by Django 4.2 on 2024-09-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0013_alter_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
    ]
