# Generated by Django 4.2 on 2024-09-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0014_alter_service_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service1',
            name='icon1',
            field=models.ImageField(blank=True, null=True, upload_to='service_icons/'),
        ),
    ]
