# Generated by Django 4.2 on 2024-09-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0016_additionalimage_blog_category_tag_blogdetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='internal_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/'),
        ),
    ]
