# Generated by Django 4.2 on 2024-09-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0017_blog_internal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_related',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/'),
        ),
    ]
