# Generated by Django 5.1.1 on 2024-09-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0020_portfolioproject_image1_portfolioproject_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
